export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAILED = 'ALL_PRODUCTS_FAILED'

export const CART_TO_ADDREQUEST = 'CART_TO_ADDREQUEST'
export const CART_TO_ADDSUCCESS = 'CART_TO_ADDSUCCESS'
export const CART_TO_ADDFAILED = 'CART_TO_ADDFAILED'
export const CART_TO_REMOVE = 'CART_TO_REMOVE'
export const CART_TO_SHOPPING= 'CART_TO_SHOPPING'

export const ONE_PRODUCTS_REQUEST = 'ONE_PRODUCTS_REQUEST'
export const ONE_PRODUCTS_SUCCESS = 'ONE_PRODUCTS_SUCCESS'
export const ONE_PRODUCTS_FAILED = 'ONE_PRODUCTS_FAILED'


export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'


export const USER_DELET_REQUEST='USER_DELET_REQUEST'
export const USER_DELET_SUCCESS='USER_DELET_SUCCESS'
export const USER_DELET_FAILED='USER_DELET_FAILED'
export const USER_DELET_RESET='USER_DELET_RESET'  

export const ORDER_ITEM_REQUEST='ORDER_ITEEM_SUCCESS'
export const ORDER_ITEM_FAILED='ORDER_ITM_REQUEST'
export const ORDER_ITEM_SUCCESS='ORDER_ITEM_FAILED'


export const USER_SIGNIN_REQUEST='USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED='USER_SIGNIN_FAILED'
export const USER_SIGNIN='USER_SIGNIN'